### ISSUE TITLE
IndexError: list index out

### ISSUE THREAD

**Issue by diogosimao** [imnotjames/notion-docs-sync#2]
```
Traceback (most recent call last):
  File "/usr/local/bin/notion-docs-sync", line 33, in <module>
    sys.exit(load_entry_point('notion-docs-sync', 'console_scripts', 'notion-docs-sync')())
  File "/app/notion_docs_sync/__init__.py", line 327, in main
    client = NotionClient(token_v2=token)
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 68, in __init__
    self._update_user_info()
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 77, in _update_user_info
    self.current_space = self.get_space(list(records["space"].keys())[0])
IndexError: list index out
```
I have no idea where it came from... if you need more info let me know!

**Comment by imnotjames** [comment]
It could be that the API has changed a bit - but this seems like it might be an upstream issue?  Not sure.

Were you just trying to run it at all?

Or was there a specific scenario that you ended p seeing this happen with?
