### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by DavidSongzw** [imnotjames/notion-docs-sync#3]
Creating page structure..
Syncing /github/workspace/README.md to block 30c67eb0-cccd-4fce-aa35-66e747e837ba
Using existing markdown block 2ed797af-f250-4055-984b-a09012b5f491 in 30c67eb0-cccd-4fce-aa35-66e747e837ba
Using existing markdown block f925ff86-26a1-4bd7-96a4-ed28eefe7f38 in 30c67eb0-cccd-4fce-aa35-66e747e837ba
Moving page bf5dcc7c-2116-4228-9577-60e99dbaa88a to end of 30c67eb0-cccd-4fce-aa35-66e747e837ba
Traceback (most recent call last):
  File "/usr/local/bin/notion-docs-sync", line 33, in <module>
    sys.exit(load_entry_point('notion-docs-sync', 'console_scripts', 'notion-docs-sync')())
  File "/app/notion_docs_sync/__init__.py", line 330, in main
    sync_directory_to_block(docs_path, root_block)
  File "/app/notion_docs_sync/__init__.py", line 299, in sync_directory_to_block
    move_pages_to_end(block)
  File "/app/notion_docs_sync/__init__.py", line 79, in move_pages_to_end
    page.move_to(block, 'last-child')
  File "/usr/local/lib/python3.8/site-packages/notion/block.py", line 419, in move_to
    self._client.refresh_records(
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 165, in refresh_records
    self._store.call_get_record_values(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/notion/store.py", line 254, in call_get_record_values
    results = self._client.post(
  File "/usr/local/lib/python3.8/site-packages/notion/client.py", line 183, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.

**Comment by NicolasTobias** [comment]
Me too having this error. Any update?

**Comment by reubenwenisch** [comment]
Same here
